### ISSUE TITLE
TypeError when checking links on a Hugo site

### ISSUE THREAD

**Issue by nikoheikkila** [Munter/netlify-plugin-checklinks#44]
Hi, I just tried to include this on a Hugo static site build with default plugin values. However, the build on a pull request fails to a type error.

**EDIT:** Just discovered that this error also happens with https://github.com/Munter/netlify-plugin-subfont plugin so the issue might be somewhere else. 🤔 

**Build output**

```
11:50:52 AM: ┌───────────────────────────────────────────────────┐
11:50:52 AM: │ Plugin "netlify-plugin-checklinks" internal error │
11:50:52 AM: └───────────────────────────────────────────────────┘
11:50:52 AM: ​
11:50:52 AM:   Error message
11:50:52 AM:   TypeError: Patterns must be a string or an array of strings
11:50:52 AM: ​
11:50:52 AM:   Plugin details
11:50:52 AM:   ID:             netlify-plugin-checklinks
11:50:52 AM:   Version:        4.0.0
11:50:52 AM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
11:50:52 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
11:50:52 AM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
11:50:52 AM: ​
11:50:52 AM:   Error location
11:50:52 AM:   In "onPostBuild" event in npm package "netlify-plugin-checklinks"
11:50:52 AM:       at assertPatternsInput (/opt/build/repo/node_modules/globby/index.js:16:9)
11:50:52 AM:       at generateGlobTasks (/opt/build/repo/node_modules/globby/index.js:41:2)
11:50:52 AM:       at AsyncFunction.module.exports.sync (/opt/build/repo/node_modules/globby/index.js:139:20)
11:50:52 AM:       at onPostBuild (/opt/build/repo/node_modules/netlify-plugin-checklinks/lib/index.js:48:27)
11:50:52 AM:       at Object.run (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/child/main.js:86:9)
11:50:52 AM:       at handleEvent (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/child/main.js:67:43)
11:50:52 AM:       at getEventsFromParent (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/child/main.js:63:61)
11:50:52 AM:       at process.on (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/ipc.js:97:15)
11:50:52 AM:       at process.emit (events.js:198:13)
11:50:52 AM:       at emit (internal/child_process.js:832:12)
11:50:52 AM:       at process._tickCallback (internal/process/next_tick.js:63:19)
```

Any suggestions? I can provide more info where needed.

**Comment by Munter** [comment]
This is most certainly a bug. Probably due to lack of tests while upgrading through the breaking changes of netlify-build. I'll see if I can have a look at this in the weekend

**Comment by Munter** [comment]
I am having a bit of trouble recreating this situation with valid inputs. These are that I've tried:

```toml
  [plugins.inputs]
  # Default value, start with all html-files in the root
  entryPoints = ['*.html']
```

```toml
  [plugins.inputs]
  # Commented out, undefined should fall back to default values
  # entryPoints = ['*.html']
```

```toml
  [plugins.inputs]
  # No glob patterns. Yields no entry points, thus doesn't check anything
  entryPoints = []
```

I've even tried adding a glob pattern string directly instead of passing an array. It works, byt completely incidentally because I pass the input directly to `globby`, which supports a srtring:

```toml
  [plugins.inputs]
  entryPoints = '*.html'
```

I am assuming that you accidentally misconfigured the plugin. There's still a regression at play though. In a previous version of netlify build you could specify input validation with a json schema, which I did. All input would be validated and get assigned default values if undefined. The new version of netlify build doesn't have input validation, only default assignment. So I'm assuming a misconfiguration that passed invalid values down the stack and then it throws. Can you confirm this hypothesis?

**Comment by codedge** [comment]
@Munter I can confirm the error @nikoheikkila has still exists, with the following `netlify.toml`

```toml
[context.production.environment]
HUGO_VERSION = "0.69.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

NODE_VERSION = "13"

[build]
publish = "public"
command = "hugo --gc --minify"


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
package = "netlify-plugin-debug-cache"

[[plugins]]
package = "netlify-plugin-checklinks"
```

**Error**

```
2:15:50 PM: Build ready to start
2:15:51 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
2:15:51 PM: build-image tag: v3.3.7
2:15:51 PM: buildbot version: 134ec431c6a3ff76e87cc4dc34007fe13842272f
2:15:52 PM: Fetching cached dependencies
2:15:52 PM: Starting to download cache of 253.4MB
2:15:54 PM: Finished downloading cache in 2.173026718s
2:15:54 PM: Starting to extract cache
2:16:01 PM: Finished extracting cache in 7.392144322s
2:16:01 PM: Finished fetching cache in 9.827486815s
2:16:01 PM: Starting to prepare the repo for build
2:16:02 PM: Preparing Git Reference refs/heads/master
2:16:05 PM: Starting build script
2:16:05 PM: Installing dependencies
2:16:05 PM: Started restoring cached node version
2:16:11 PM: Finished restoring cached node version
2:16:12 PM: v13.13.0 is already installed.
2:16:13 PM: Now using node v13.13.0 (npm v6.14.4)
2:16:13 PM: Attempting ruby version 2.6.2, read from environment
2:16:14 PM: Using ruby version 2.6.2
2:16:14 PM: Using PHP version 5.6
2:16:14 PM: Installing Hugo 0.69.0
2:16:14 PM: Hugo Static Site Generator v0.69.0-4205844B/extended linux/amd64 BuildDate: 2020-04-10T09:16:58Z
2:16:14 PM: Started restoring cached go cache
2:16:14 PM: Finished restoring cached go cache
2:16:15 PM: unset GOOS;
2:16:15 PM: unset GOARCH;
2:16:15 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
2:16:15 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
2:16:15 PM: go version >&2;
2:16:15 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
2:16:15 PM: go version go1.12 linux/amd64
2:16:15 PM: Installing missing commands
2:16:15 PM: Verify run directory
2:16:18 PM: Resolved Netlify Build version tag "latest" to "0.3.6"
2:16:18 PM: Netlify Build not installed. Installing Netlify Build version 0.3.6
2:16:38 PM: /opt/buildhome/.nvm/versions/node/v12.16.1/bin/netlify-build -> /opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/core/bin.js
2:16:39 PM: + @netlify/build@0.3.6
2:16:39 PM: added 583 packages from 324 contributors in 20.112s
2:16:40 PM: Starting Netlify Build...
2:16:42 PM: ​
2:16:42 PM: ┌─────────────────────────────┐
2:16:42 PM: │        Netlify Build        │
2:16:42 PM: └─────────────────────────────┘
2:16:42 PM: ​
2:16:42 PM: ❯ Version
2:16:42 PM:   @netlify/build 0.3.6
2:16:42 PM: ​
2:16:42 PM: ❯ Flags
2:16:42 PM:   mode: buildbot
2:16:42 PM: ​
2:16:42 PM: ❯ Current directory
2:16:42 PM:   /opt/build/repo
2:16:42 PM: ​
2:16:42 PM: ❯ Config file
2:16:42 PM:   /opt/build/repo/netlify.toml
2:16:42 PM: ​
2:16:42 PM: ❯ Context
2:16:42 PM:   production
2:16:42 PM: ​
2:16:42 PM: ❯ Installing plugins
2:16:42 PM:    - netlify-plugin-debug-cache
2:16:42 PM:    - netlify-plugin-checklinks
2:17:02 PM: ​
2:17:02 PM: ❯ Loading plugins
2:17:02 PM:    - netlify-plugin-debug-cache@1.0.1
2:17:02 PM:    - netlify-plugin-checklinks@4.0.0
2:17:03 PM: ​
2:17:03 PM: ┌──────────────────────────────────────────────────────────────────┐
2:17:03 PM: │ 1. build.lifecycle.onBuild command from netlify.toml config file │
2:17:03 PM: └──────────────────────────────────────────────────────────────────┘
2:17:03 PM: ​
2:17:03 PM: $ hugo --gc --minify
2:17:03 PM: Building sites …
2:17:03 PM:                    | EN
2:17:03 PM: -------------------+------
2:17:03 PM:   Pages            |  13
2:17:03 PM:   Paginator pages  |   0
2:17:03 PM:   Non-page files   |   0
2:17:03 PM:   Static files     | 102
2:17:03 PM:   Processed images |   0
2:17:03 PM:   Aliases          |   3
2:17:03 PM:   Sitemaps         |   1
2:17:03 PM:   Cleaned          |   0
2:17:03 PM: Total in 166 ms
2:17:03 PM: ​
2:17:03 PM: (build.lifecycle.onBuild completed in 223ms)
2:17:03 PM: ​
2:17:03 PM: ┌───────────────────────────────────────────────────────┐
2:17:03 PM: │ 2. onPostBuild command from netlify-plugin-checklinks │
2:17:03 PM: └───────────────────────────────────────────────────────┘
2:17:03 PM: ​
2:17:03 PM: ​
2:17:03 PM: ┌──────────────────────────────────────────────────┐
2:17:03 PM: │ 3. onEnd command from netlify-plugin-debug-cache │
2:17:03 PM: └──────────────────────────────────────────────────┘
2:17:03 PM: ​
2:17:04 PM: Saving cache file manifest for debugging...
2:17:04 PM: Cache file count: 33829
2:17:04 PM: Cache manifest saved to public/cache-output.json
2:17:04 PM: Please download the build files to inspect cache-output.json.
2:17:04 PM: Instructions => http://bit.ly/netlify-dl-cache
2:17:04 PM: ​
2:17:04 PM: (netlify-plugin-debug-cache onEnd completed in 1s)
2:17:04 PM: ​
2:17:04 PM: ┌───────────────────────────────────────────────────┐
2:17:04 PM: │ Plugin "netlify-plugin-checklinks" internal error │
2:17:04 PM: └───────────────────────────────────────────────────┘
2:17:04 PM: ​
2:17:04 PM:   Error message
2:17:04 PM:   TypeError: Patterns must be a string or an array of strings
2:17:04 PM: ​
2:17:04 PM:   Plugin details
2:17:04 PM:   ID:             netlify-plugin-checklinks
2:17:04 PM:   Version:        4.0.0
2:17:04 PM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
2:17:04 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
2:17:04 PM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
2:17:04 PM: ​
2:17:04 PM:   Error location
2:17:04 PM:   In "onPostBuild" event in npm package "netlify-plugin-checklinks"
2:17:04 PM:       at assertPatternsInput (/opt/build/repo/node_modules/globby/index.js:16:9)
2:17:04 PM:       at generateGlobTasks (/opt/build/repo/node_modules/globby/index.js:41:2)
2:17:04 PM:       at AsyncFunction.module.exports.sync (/opt/build/repo/node_modules/globby/index.js:139:20)
2:17:04 PM:       at onPostBuild (/opt/build/repo/node_modules/netlify-plugin-checklinks/lib/index.js:48:27)
2:17:04 PM:       at Object.run (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/child/main.js:86:9)
2:17:04 PM:       at handleEvent (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/child/main.js:67:43)
2:17:04 PM:       at /opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/child/main.js:63:61
2:17:04 PM:       at process.<anonymous> (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/plugins/ipc.js:97:15)
2:17:04 PM:       at process.emit (events.js:315:20)
2:17:04 PM:       at emit (internal/child_process.js:881:12)
2:17:04 PM:       at processTicksAndRejections (internal/process/task_queues.js:85:21)
2:17:04 PM: ​
2:17:05 PM: Caching artifacts
2:17:05 PM: Started saving node modules
2:17:05 PM: Finished saving node modules
2:17:05 PM: Started saving pip cache
2:17:05 PM: Finished saving pip cache
2:17:05 PM: Started saving emacs cask dependencies
2:17:05 PM: Finished saving emacs cask dependencies
2:17:05 PM: Started saving maven dependencies
2:17:05 PM: Finished saving maven dependencies
2:17:05 PM: Started saving boot dependencies
2:17:05 PM: Finished saving boot dependencies
2:17:05 PM: Started saving go dependencies
2:17:05 PM: Finished saving go dependencies
2:17:05 PM: Error running command: Build script returned non-zero exit code: 1
2:17:05 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:17:05 PM: Failing build: Failed to build site
2:17:05 PM: Finished processing build request in 1m13.674117072s
```

At least for me, I don't think / cannot confirm this is a configuration issue, as I don't configure anything for the plugin. Further when I remove the plugin from my `netlify.toml` the build is passing fine.

**Comment by Munter** [comment]
I think I found it. Migrating from json schema validation to netlify build plugin menifest yaml moved the manifest file to the root of the repo. My `files` property in `package.json` only includes `/lib` and thus `manifest.yml` is not a part of the distributed package. This means you will get no default values applied.

I didn't spot this because all tests of the repository are testing in an environment where `manifest.yml` does exist in the local file system.

Ping @davidwells : I accidentally didn't publish the `manifest.yml` file in my netlify plugin npm package, and netlify build didn't check for its existence. Could we make netlify build do a double check and throw a precise error in this case?

@nikoheikkila @codedge I'll fix this up and release new versions of all my plugins in a few hours

**Comment by Munter** [comment]
Fixed in v4.0.1

Thanks for the detailed information to help me recreate

**Comment by codedge** [comment]
Hey Munter, just checked with the new version.

I still get an error.

<img width="970" alt="grafik" src="https://user-images.githubusercontent.com/4409904/79728981-12a7c180-82ef-11ea-81be-a0fddef02f8b.png">

**Full output**
```
10:05:41 AM: Build ready to start
10:05:43 AM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
10:05:43 AM: build-image tag: v3.3.7
10:05:43 AM: buildbot version: 134ec431c6a3ff76e87cc4dc34007fe13842272f
10:05:43 AM: Fetching cached dependencies
10:05:43 AM: Starting to download cache of 256.3MB
10:05:45 AM: Finished downloading cache in 2.254017209s
10:05:45 AM: Starting to extract cache
10:05:53 AM: Finished extracting cache in 8.078176583s
10:05:54 AM: Finished fetching cache in 10.407899198s
10:05:54 AM: Starting to prepare the repo for build
10:05:54 AM: Preparing Git Reference refs/heads/master
10:05:56 AM: Starting build script
10:05:56 AM: Installing dependencies
10:05:57 AM: Started restoring cached node version
10:06:02 AM: Finished restoring cached node version
10:06:03 AM: v13.13.0 is already installed.
10:06:03 AM: Now using node v13.13.0 (npm v6.14.4)
10:06:04 AM: Attempting ruby version 2.6.2, read from environment
10:06:05 AM: Using ruby version 2.6.2
10:06:05 AM: Using PHP version 5.6
10:06:05 AM: Installing Hugo 0.69.0
10:06:05 AM: Hugo Static Site Generator v0.69.0-4205844B/extended linux/amd64 BuildDate: 2020-04-10T09:16:58Z
10:06:05 AM: Started restoring cached go cache
10:06:05 AM: Finished restoring cached go cache
10:06:05 AM: unset GOOS;
10:06:05 AM: unset GOARCH;
10:06:05 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
10:06:05 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
10:06:05 AM: go version >&2;
10:06:05 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
10:06:05 AM: go version go1.12 linux/amd64
10:06:05 AM: Installing missing commands
10:06:05 AM: Verify run directory
10:06:08 AM: Resolved Netlify Build version tag "latest" to "0.3.6"
10:06:08 AM: Netlify Build not installed. Installing Netlify Build version 0.3.6
10:06:31 AM: /opt/buildhome/.nvm/versions/node/v12.16.1/bin/netlify-build -> /opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/src/core/bin.js
10:06:32 AM: + @netlify/build@0.3.6
10:06:32 AM: added 583 packages from 324 contributors in 22.938s
10:06:32 AM: Starting Netlify Build...
10:06:34 AM: ​
10:06:34 AM: ┌─────────────────────────────┐
10:06:34 AM: │        Netlify Build        │
10:06:34 AM: └─────────────────────────────┘
10:06:34 AM: ​
10:06:34 AM: ❯ Version
10:06:34 AM:   @netlify/build 0.3.6
10:06:34 AM: ​
10:06:34 AM: ❯ Flags
10:06:34 AM:   mode: buildbot
10:06:34 AM: ​
10:06:34 AM: ❯ Current directory
10:06:34 AM:   /opt/build/repo
10:06:34 AM: ​
10:06:34 AM: ❯ Config file
10:06:34 AM:   /opt/build/repo/netlify.toml
10:06:34 AM: ​
10:06:34 AM: ❯ Context
10:06:34 AM:   production
10:06:34 AM: ​
10:06:34 AM: ❯ Installing plugins
10:06:34 AM:    - netlify-plugin-checklinks
10:06:59 AM: ​
10:06:59 AM: ❯ Loading plugins
10:07:00 AM:    - netlify-plugin-checklinks@4.0.1
10:07:00 AM: ​
10:07:00 AM: ┌──────────────────────────────────────────────────────────────────┐
10:07:00 AM: │ 1. build.lifecycle.onBuild command from netlify.toml config file │
10:07:00 AM: └──────────────────────────────────────────────────────────────────┘
10:07:00 AM: ​
10:07:00 AM: $ hugo --gc --minify
10:07:00 AM: Building sites …
10:07:00 AM:                    | EN
10:07:00 AM: -------------------+------
10:07:00 AM:   Pages            |  14
10:07:00 AM:   Paginator pages  |   0
10:07:00 AM:   Non-page files   |   0
10:07:00 AM:   Static files     | 112
10:07:00 AM:   Processed images |   0
10:07:00 AM:   Aliases          |   3
10:07:00 AM:   Sitemaps         |   1
10:07:00 AM:   Cleaned          |   0
10:07:00 AM: Total in 256 ms
10:07:00 AM: ​
10:07:00 AM: (build.lifecycle.onBuild completed in 314ms)
10:07:00 AM: ​
10:07:00 AM: ┌───────────────────────────────────────────────────────┐
10:07:00 AM: │ 2. onPostBuild command from netlify-plugin-checklinks │
10:07:00 AM: └───────────────────────────────────────────────────────┘
10:07:00 AM: ​
10:07:02 AM: ..×.............................................................................................
10:07:02 AM:   ✖ FAIL load public/site.webmanifest
10:07:02 AM:   | operator: load
10:07:02 AM:   | expected: 200 public/site.webmanifest
10:07:02 AM:   |   actual: ENOENT: no such file or directory, open '/opt/build/repo/public/site.webmanifest'
10:07:02 AM:   |       at: public/404.html:1:1453 <link rel="manifest" href="/site.webmanifest">
10:07:02 AM:   96 tests
10:07:02 AM:   95 passed
10:07:02 AM:    1 failed
10:07:02 AM: ​
10:07:02 AM: ┌─────────────────────────────┐
10:07:02 AM: │        Build failed         │
10:07:02 AM: └─────────────────────────────┘
10:07:02 AM: ​
10:07:02 AM:   Error message
10:07:02 AM:   Error: Links checking failed
10:07:02 AM: ​
10:07:02 AM:   Plugin details
10:07:02 AM:   ID:             netlify-plugin-checklinks
10:07:02 AM:   Version:        4.0.1
10:07:02 AM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
10:07:02 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
10:07:02 AM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
10:07:02 AM: ​
10:07:02 AM:   Error location
10:07:02 AM:   In "onPostBuild" event in npm package "netlify-plugin-checklinks"
10:07:02 AM:       at onPostBuild (/node_modules/netlify-plugin-checklinks/lib/index.js:62:14)
10:07:02 AM: ​
10:07:03 AM: Caching artifacts
10:07:03 AM: Started saving node modules
10:07:03 AM: Finished saving node modules
10:07:03 AM: Started saving pip cache
10:07:03 AM: Finished saving pip cache
10:07:03 AM: Started saving emacs cask dependencies
10:07:04 AM: Finished saving emacs cask dependencies
10:07:04 AM: Started saving maven dependencies
10:07:04 AM: Finished saving maven dependencies
10:07:04 AM: Started saving boot dependencies
10:07:04 AM: Finished saving boot dependencies
10:07:04 AM: Started saving go dependencies
10:07:04 AM: Finished saving go dependencies
10:07:04 AM: Error running command: Build script returned non-zero exit code: 1
10:07:04 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:07:04 AM: Failing build: Failed to build site
10:07:04 AM: Finished processing build request in 1m20.735435015s
```

Does that mean I need to have `site.webmanifest` file?

**Comment by codedge** [comment]
After adding the `site.manifest` to the `static` folder it runs without issues. Thanks @Munter for the quick fix. 👍

**Comment by nikoheikkila** [comment]
Thanks for fixing this!

> After adding the `site.manifest` to the `static` folder it runs without issues. Thanks @Munter for the quick fix. 👍

@codedge Can you share what should be in the `site.manifest` file?

**Comment by codedge** [comment]
I took the content from https://developer.mozilla.org/en-US/docs/Web/Manifest. So my `site.manifest` file looks like this:

```
{
    "name": "My site name",
    "short_name": "Short name for my site",
    "start_url": ".",
    "icons": [
        {
            "src": "/favicon-32x32.png",
            "sizes": "32x32",
            "type": "image/png"
        },
        {
            "src": "/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
        
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
}
```

I used this site to generate the different icons and the `site.manifest` itself. Hope this helps.

**Comment by nikoheikkila** [comment]
Hi, confirmed everything is working after adding the manifest. Thanks again!
